"""시뮬레이터와 분리된 학습 구성요소와 RL-PINN 보조 손실."""

from learning.physics_loss import (
    PhysicsLossBreakdown,
    detached_target_least_squares,
    macro_adr_loss,
    micro_dynamics_loss,
    project_torch_parameters,
    ridge_least_squares_2row,
    soft_cap_nonnegative_loss,
)
from learning.trajectory_loss import (
    ExactMacroLoss,
    ExactMicroLoss,
    ExactPhysicsLoss,
    TorchDensityTrajectory,
    exact_macro_adr_loss,
    exact_macro_loss_from_context,
    exact_micro_edm_loss,
    exact_micro_loss_from_context,
    exact_physics_loss_from_context,
    interpolate_phase_agent_values,
    reconstruct_phase_density_torch,
    spatial_divergence_2d,
)
from learning.rollout_context import (
    MACRO_CONTEXT_KEYS,
    MICRO_CONTEXT_KEYS,
    PhysicsContextBuffer,
    body_to_world_vectors,
    build_physics_transition,
    build_micro_transition,
    phase_indices_from_one_hot,
    record_physics_transition,
)

__all__ = [
    "PhysicsLossBreakdown",
    "MACRO_CONTEXT_KEYS",
    "MICRO_CONTEXT_KEYS",
    "PhysicsContextBuffer",
    "ExactMacroLoss",
    "ExactMicroLoss",
    "ExactPhysicsLoss",
    "TorchDensityTrajectory",
    "body_to_world_vectors",
    "build_physics_transition",
    "build_micro_transition",
    "detached_target_least_squares",
    "exact_macro_adr_loss",
    "exact_macro_loss_from_context",
    "exact_micro_edm_loss",
    "exact_micro_loss_from_context",
    "exact_physics_loss_from_context",
    "interpolate_phase_agent_values",
    "macro_adr_loss",
    "micro_dynamics_loss",
    "phase_indices_from_one_hot",
    "project_torch_parameters",
    "ridge_least_squares_2row",
    "reconstruct_phase_density_torch",
    "record_physics_transition",
    "spatial_divergence_2d",
    "soft_cap_nonnegative_loss",
]
